#!/bin/bash

cd /home/ubuntu

sudo sudo apt-get install build-essential libssl-dev -y

curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh -o install_nvm.sh
chmod +x install_nvm.sh
bash ./install_nvm.sh -y
rm ./install_nvm.sh

source ~/.profile

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

nvm install 12.18 -y

npm install pm2 -g

cd /home/ubuntu/src

pm2 stop all
pm2 start ./index.js
